name: Build mohadeseh gym


on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install packages
      shell: bash
      run: |

        sudo apt-get update

        sudo apt-get install -y \
          python3-pip \
          git \
          unzip \
          openjdk-17-jdk \
          wget



    - name: Install build tools
      shell: bash
      run: |

        python3 -m pip install --user --upgrade pip

        python3 -m pip install --user \
          buildozer \
          cython==0.29.36



    - name: Setup Android SDK
      shell: bash
      run: |

        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk


        mkdir -p $ANDROID_HOME/cmdline-tools


        cd /tmp


        wget -q \
        https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip


        unzip -q commandlinetools-linux-11076708_latest.zip


        mkdir -p $ANDROID_HOME/cmdline-tools/latest


        mv cmdline-tools/* \
        $ANDROID_HOME/cmdline-tools/latest/


        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin


        yes | sdkmanager --licenses || true


        sdkmanager \
        "platform-tools" \
        "platforms;android-35" \
        "build-tools;35.0.0"



    - name: Fix sdkmanager compatibility
      shell: bash
      run: |

        SDK=$HOME/.buildozer/android/platform/android-sdk


        mkdir -p $SDK/tools/bin


        ln -sf \
        $SDK/cmdline-tools/latest/bin/sdkmanager \
        $SDK/tools/bin/sdkmanager



    - name: Build mohadeseh gym APK
      shell: bash
      run: |

        export PATH=$PATH:$HOME/.local/bin


        buildozer android debug



    - name: Upload APK
      uses: actions/upload-artifact@v4

      with:

        name: mohadeseh-gym-apk

        path: bin/*.apk
