name: Build mohadeseh gym APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y \
          python3 \
          python3-pip \
          python3-venv \
          git \
          unzip \
          wget \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          build-essential

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --user buildozer cython==0.29.37

    - name: Prepare Android licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses

        echo 24333f8a63b6825ea9c5514f83c2829b004d1fee > \
        ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

        echo 84831b9409646a918e30573bab4c9c91346d8abd > \
        ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

    - name: Build
      run: |
        export PATH=$PATH:$HOME/.local/bin

        rm -rf .buildozer

        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mohadeseh-gym
        path: bin/*.apk
